name: 'Slack Notification - Basic'

on:
  workflow_dispatch:
  push:
    branches: [ main, develop , feature/**]

  
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
      
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      
      - name: 'Send Slack Notification'
        uses: samuelBarreto/Action-Slack@main
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}


      - name: 'Send Slack Notification teste'
        uses: samuelBarreto/Action-Slack@main
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#deployments'
          username: 'Deploy Bot'
          icon-emoji: ':rocket:'
          include-event-details: 'true' 